### ISSUE TITLE
Seeking and changing sources on HTMLMediaElement

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-fromelement#10]
I think that we have to consider seeking to be equivalent to changing sources.  That has different ramifications for `captureStream` and `captureStreamUntilEnded`.

**Comment by Pehrsons** [comment]
I talked a bit about this face to face with JW Wang (mozilla) today and he was of the opinion that tracks should only end when the stream ends, i.e., when the media element issues the "ended" event.

I agree with him on this as it is closer to how media playback works:
- You get "loadedmetadata" containing a fixed set of tracks for a media, it doesn't matter when they start or end in the media.
- You can select/enable tracks from when they are known ("loadedmetadata") and they stay the same through seeks and pauses until the media ends. Selected/enabled tracks define which tracks exist in the captureStream() stream, so it makes sense if they also stay the same until the media ends.
- If you select an audio track that hasn't started, it will play silence until its start (though identical to "do not play anything" anyway). Likewise after it ends. It's simpler for video as the stream could just send the media element's current frame.

Also, the way the proposal stands right now, a paused media element outputs silence/last-frame, so having it do the same while seeking would make the specification simpler and more consistent.

It would also simplify life for JS programmers. Consider the cases:
- When a `captureStream()` stream is sent over a PeerConnection, a seek implies that the implementer does some RtpSender.replaceTrack() magic to continue sending data.
  - If tracks don't end on seek one would not have to bother until the source changes.
- When a `captureStream()` stream is recorded by a MediaRecorder, a seek would, to my interpretation of the current editor's draft, mean that an "error" event is raised since the set of tracks changed but the stream didn't end, unless `stop()` was called first. If the MediaRecorder can handle the track changes (both remove and add), the resulting media file would have n*i tracks when loaded in a media element, where n is the amount of seeks during recording, and i is the amount of tracks present in the media.
  - If tracks don't end on seek the resulting media file would resemble the original in terms of its track set unless it captured multiple sources.

**Comment by martinthomson** [comment]
@Pehrsons, I'm just going through the spec and trying to play through the ramifications of your proposed changed view.  Unless I'm mistaken, the distinction between `captureStream` and `captureStreamUntilEnded` would disappear.  You simply capture what is rendered until playback stops.  Is that right?

One concern I have relates to the multiple audio capture thing.  Assuming that we have audio tracks that start and end at different times, then we can't reflect them using the real-time `MediaStreamTrack` interface, which doesn't natively have this concept.  The only options I see are to have the tracks added as soon as we know about them and play silence until they start properly, or to have them added when they start.  At the other end of things, we can have them stop when they stop, but we wouldn't be able to handle a seek at that point because an ended `MediaStreamTrack` can't be un-stopped.

Does this suggest that we need a new `active` attribute on a track so that we can mark them as actively producing media?

I'm actually surprised that video tracks are selected exclusively based on this model.  Do they not have start and end times in the same way that audio does?  I guess the answer is that it is not practical to structure video in this fashion, because you would have to manually switch between video tracks and you would inevitably get the changeover wrong.

**Comment by Pehrsons** [comment]
`captureStreamUntilEnded` could still be defined so that it ends (no more tracks would get added) when the media ends (i.e., when the media element fires the "ended" event). Whereas `captureStream` simply captures what is rendered at all times.

I think we can let the track selection itself define which tracks are available in the stream, i.e., select two audio tracks and they would get added (if not already) to the stream; then select one of these and the other gets removed from the stream.

While a track is present but has not yet started or has already ended, we can perhaps let the `mute` property be true to indicate that it is inactive. Or we just play silence/last-frame, I don't really have an opinion on that.

> At the other end of things, we can have them stop when they stop, but we wouldn't be able to handle a seek at that point because an ended MediaStreamTrack can't be un-stopped.

I think the tracks should not end until the playback of the entire media file has ended. This more closely reflects how a media element works. In a media element you are able to seek when one of the tracks have ended and it will still render that track after the seek. With your suggestion to end the corresponding track in the stream after the track has ended in the media (but before the entire playback has ended) we'd get into a rare corner case that is not easily understood by users (the original video track 'froze' and a new appeared). It's my understanding that, at least in the vast majority of cases, all tracks in a media start and end at the same time, but due to various reasons (be it editing, encoding or timing related) this is not always the case. Thus the duration for when only some tracks are present is typically very small and seeking in this time frame would probably lead to confusion with users - suspicion of bugs in the user agent, etc.

> I'm actually surprised that video tracks are selected exclusively based on this model. Do they not have start and end times in the same way that audio does? I guess the answer is that it is not practical to structure video in this fashion, because you would have to manually switch between video tracks and you would inevitably get the changeover wrong.

Not sure I follow what you mean here, but I believe video tracks are exclusively selected because a video element can only render one of them at the same time. A way to show two video tracks from the same media (different camera angles, maybe) side by side would actually be to have captureStream() output all tracks independently of their selected status to a stream and play that stream in several video elements. That would be the only way to my knowledge that we can keep both those tracks in sync. Is this a case we have considered? The spec currently prohibits it since it only makes available tracks that have been selected or enabled in the media element.

**Comment by martinthomson** [comment]
I think that I can work with that, thanks.  Marking tracks as `muted` prior to starting and after ending works for me.

With respect to exclusive selection of video, the situation is analogous to the audio one where you have two tracks that don't play at the same time.  For example, if track 1 ends immediately before track 2 starts.  If both are present and selected, the net effect is that there is a single continuous audio playback, indistinguishable from the case where there is a single track.  However, you can't do the same with video (unless you had (z-)ordering and alpha channels, I guess).  It's manageable, but odd, that's all.

**Comment by martinthomson** [comment]
@Pehrsons can you take a look at the PR?  I've got a few comments from Shijun that I need to address, but they are minor.

**Comment by Pehrsons** [comment]
There you go. I gave you some comments as well, nothing major.
