### ISSUE TITLE
Use with MediaSource

### ISSUE THREAD

**Issue by max-mapper** [w3c/mediacapture-fromelement#19]
Hi, I'm excited about this spec and about if it is designed to work well with MediaSource. 

E.g. if I create a custom MediaSource instance with `new MediaSource()` and acquire my own custom media stream via file/network I/O and hook it up to my MediaSource instance ([as is done here](https://gist.github.com/maxogden/108134f035decfcfdf15)), and then do `video.src = window.URL.createObjectURL(mediaSource)` to render it in a `<video>` tag, does that mean I can use `var captureStream = video.captureStream()` to transmit my custom MediaSource data over an e.g. WebRTC PeerConnection using `peerConnection.addStream(captureStream)`?

It seems a little unnecessary to me to have to use a `<video>` tag at all to send data from a `MediaSource` over a `PeerConnection`, is there another way? `PeerConnection` only accepts `MediaStream` instances and from what I can tell it seems this new `video.captureStream` method will be the only way to get a `MediaStream` instance from a `MediaSource`.

Also, will there be any performance downside to 'routing' the `MediaSource` through a `<video>` element, when I don't actually wan't to display the `<video>` element in the DOM, I just want to use it to get a capture stream? E.g. does this result in my video being re-encoded?

**Comment by martinthomson** [comment]
This is probably not the right venue for a question, but I'll leave the issue open to track decisions regarding the interaction between the APIs.

No, you can't use `MediaSource` directly.  We might decide to support that later.

As for performance costs, there are no costs involved with the intermediate step on `<video>`

**Comment by mhofman** [comment]
When you look at it, there are 2 types of Medias in the Web Platform: "real-time" media that is associated to a clock (webcam, microphone, webrtc stream), and "offline" media that has a controllable playback time (pause, seek, etc).
`MediaStream` objects only represent real-time media. There is no unique object to represent an offline media.
(I honestly don't have better words to separate the 2, if there are more official way to refer to these types, please enlighten me)

Now the 2 types of media are currently quite siloed in the Web Platform. What's worse is that the models are different for Audio and Video.
In the Web Audio case, you have 2 different context objects (`AudioContext` and `OfflineAudioContext`) depending on the type of media you're dealing with. I believe only the real-time context can be hooked (sink or source) to an `HTMLMediaElement` or `MediaStream`.

Interestingly, the `MediaSource` API provides a way to hook offline media into an `HTMLMediaElement`, but not to a `MediaStream`. This makes since you'd need a timing source to make the media "real-time". This is exactly what the `HTMLMediaElement` does, it provides timing control (play, pause, seek, etc.)

Going through an `HTMLMediaElement` to control timing does seem a little weird, but doing anything else is probably a question for the broader Web Platform on how to unify all the Media APIs. Regardless, you'd need some kind of object between `MediaSource` and `MediaStream` to create the timing source.

There are a lot of other discrepancies. To name a couple:
- `MediaRecorder` allows you to go from a timed media to an "offline" buffer, basically the mirror of `MediaSource` API. Yet the objects involved are different: `Blob` for `MediaRecorder` and `ArrayBuffer` or `ReadableStream` for `MediaSource`
- `MediaSource` is hooked to `HTMLMediaElement` using the `src` attribute where `MediaStream` uses `srcObject`

**Comment by max-mapper** [comment]
@mhofman Thank you, that helps clear up the back story for me. This seems like a perfect opportunity to use the the [Streams API](https://streams.spec.whatwg.org/), I wonder if this has been considered for MediaStream?

It would be nice if I could implement by own "MediaStream-like" instance in user-land instead of being forced to use the pre-constructed and opaque ones I get such as `LocalMediaStream`, similar to how you can use `new MediaSource` to implement a custom instance backed by your own buffers.

**Comment by padenot** [comment]
Relevant: https://github.com/w3c/mediacapture-worker/issues/33#issuecomment-153284128.

Anecdotally, at Mozilla, we use the terms "playback" for HTMLMediaElement, MediaSource, etc., and "real-time" for WebRTC, Web Audio API, etc. Both are clocked, but the latency expectations between producing/receiving bits of the media and playing it back are not the same (real-time is real-time, playback is simply playing back a recorded media, latency does not matter).

"Offline" is better suite for uses where there is no clock involved: video rendering in the link above, OfflineAudioContext: media is consumed and processed as fast as possible.

**Comment by martinthomson** [comment]
Closing this as not really applicable to this spec, and since we already have a solution (which is routing via HTMLMediaElement), we aren't going to do this now.  You could, if you like, propose something to WICG.
