### ISSUE TITLE
is (audio) volume supposed to be applied to the captured stream

### ISSUE THREAD

**Issue by yell0wd0g** [w3c/mediacapture-fromelement#35]
From @dalecurtis comment [here](https://github.com/w3c/mediacapture-fromelement/issues/34#issuecomment-195120737) (#34):

> As a followup question is volume supposed to be applied to the captured stream?

(Referring to the audio rendering volume of a MediaElement"

**Comment by foolip** [comment]
I think this makes sense. Edit: that playback volume has no impact, that is.

**Comment by foolip** [comment]
How about playback rate? Do implementations handle this?

**Comment by martinthomson** [comment]
@foolip 

> How about playback rate? Do implementations handle this?

I'd recommend testing this.  If Firefox doesn't, then it's just because we haven't gotten around to doing it.

**Comment by foolip** [comment]
@uysalere, how about Chromium?

**Comment by dalecurtis** [comment]
Doing this will make things a bit complicated if we're also to support muted and they are to have different meanings. Today muted just means the volume is set to zero. So if we need to distinguish between a call to muted and volume=0 it gets a bit hairy :)

As planned, there's no way to avoid playbackRate affecting the stream in Chromium.

**Comment by dalecurtis** [comment]
Oh sorry I should have read more closely. It wasn't clear that volume should have no impact. In that case you can ignore my first paragraph above.

**Comment by foolip** [comment]
So it sounds like volume/muted will have no effect will, but playback rate will. Then there's also the question of what happens if the selected video track or enabled audio track is changed. Those APIs aren't supported in Chromium yet, but when they are, should that be propagated to the `MediaStreamTrack`s? I think the answer should be yes, and the spec should say so.

Looking at `HTMLMediaElement` I can't see any more state of this kind, so that's good.

**Comment by foolip** [comment]
@avayvod, https://github.com/w3c/mediacapture-fromelement/issues/35#issuecomment-200166951 might be something to ponder.
