### ISSUE TITLE
<canvas>.captureStream() framerate parameter is too restrictive

### ISSUE THREAD

**Issue by yell0wd0g** [w3c/mediacapture-fromelement#43]
Some `<canvas>` elements produce new content in bursts, i.e. the content might not change at all and then change at a high rate, e.g. the demo in [1]. 

[`captureStream()`](https://w3c.github.io/mediacapture-fromelement/#widl-HTMLCanvasElement-captureStream-MediaStream-double-frameRate) supports either a constant, fixed frame rate or a user-defined one via `requestFrame()`. There is no support for producing a minimum frame rate, nor a frame rate between a minimum and a maximum, and either would be interesting to support e.g. recording of the captured Media Stream, or its delivery to a PeerConnection.

`captureStream()` has an optional parameter `frameRate` that can be used to specify a capture frame rate, overriding manual frame rate control; this parameter forces the said `frameRate`, hence ignoring any frame bursts. 

I propose considering supporting a `minFrameRate` and/or a `maxFrameRate` that would allow for the captured MediaStream to follow the `<canvas>` frame production while honouring the constraints.

[1] https://webrtc.github.io/samples/src/content/capture/canvas-record/

**Comment by uysalere** [comment]
I think there is a misunderstanding here. canvas.capturestream(10) does not mean canvas outputs fixed 10 fps. It means that canvas outputs 0-to-10 fps. Nothing gets captured when nothing gets painted on canvas, and 10 fps captured even if canvas gets painted 30 fps. Refer to: https://w3c.github.io/mediacapture-fromelement/#methods-1

That translates into minFrameRate=0 all the time currently. In order to implement minFrameRate>0, we would step away from the direct push model described in the spec and make copy of the snapshots. However, I don't see the benefit of sending the same frame again when there is nothing new drawn. It wouldn't cause any difference in stream attached to video tag, and it shouldn't make any difference on recorder either.

**Comment by yell0wd0g** [comment]
Re. Misunderstanding: I read, following your link:

> On creation of the captured track with a specific, non-zero frameRate, the user agent starts a periodic timer at an interval of 1/frameRate seconds. At each activation of the timer, the frameCaptureRequested property is set to true.

which, although it might be what you are describing, is hard to understand. 

IOW, if I set a `frameRate` of A fps, and the canvas produces C fps, then:
1. if C > A fps, then the MediaStream sees A fps
2. if C < A fps, then the MediaStream sees C fps? A fps?

With your description, however, then I **propose renaming** s/frameRate/maxFrameRate/, and clarifying the wording to reflect what is expected.

---

Re. differences: two of the use cases of the captured stream, e.g. MediaRecorder and PeerConnection, could benefit from having a minimal frame rate. The latter, for instance, has to go through all kinds of complicated contortions in the Chrome implementation to keep some data being put on the line for cases such as Screen/Desktop capture (where new frames are seldom produced).  The push-model can be changed to adapt to new and exciting use cases :)

**Comment by martinthomson** [comment]
maxFrameRate works for me.  frameRequestRate might work too.

Note that there was a change in the design during the process of us implementing this in Firefox.  The original design allowed for multiple samples of the same frame, which didn't make sense, either from a functional or from a performance perspective.

**Comment by ShijunS** [comment]
Since CanvasCaptureMediaStreamTrack inherits MediaStreamTrack, another option here is to use the "frameRate" constraint through MediaStreamTrack.applyConstraints().  

As a maybe orthogonal issue, the spec should define behaviors for the common ConstrainablePattern Interfaces, including applyConstraints(), whether they are applicable or not to this extension.

**Comment by martinthomson** [comment]
The intent was to have the captured stream expose the requested framerate as a constraint, which would permit changing though applyConstraints().  That probably needs clarification.

Note that we don't need to support the full set of constraints here.

**Comment by uysalere** [comment]
Proposed solution: rename it to frameRequestRate.

**Comment by martinthomson** [comment]
Note also #51.  I think that the answer there is that frobbing the "frameRate" constraint affects frameRequestRate.

**Comment by uysalere** [comment]
Merge #57 includes the rename to frameRequestRate. We can continue the discussion on using constraints in #48 or #51 .
