### ISSUE TITLE
Switch to contiguous idl

### ISSUE THREAD

**Issue by yell0wd0g** [w3c/mediacapture-fromelement#46]
Ominous warning in the ReSpec means that this Spec should be transformed to the new thing:

> Defining WebIDL in dl elements is deprecated. Please use Contiguous IDL instead: https://www.w3.org/respec/guide.html#contiguous-idl

@dontcallmedom, after doing this transition by hand elsewhere I'm more than willing to be shown your conversion script in action :-)

**Comment by dontcallmedom** [comment]
See https://github.com/w3c/mediacapture-fromelement/pull/41 :)

**Comment by yell0wd0g** [comment]
What's the status of #41, can we merge it, @dontcallmedom , @martinthomson ?

**Comment by dontcallmedom** [comment]
since you're an editor now, you can probably make that decision :)

That being said, I think the PR would need updating given the commits that were merged since it was generated. If you could review the PR in its previous state, given thumb up to the overall approach, I can then look into the best ways to update it (regenerate from source vs manual cherry-pick)

**Comment by dontcallmedom** [comment]
I realize that you didn't have write access to the repo - sorry about that, should be fixed now.

**Comment by yell0wd0g** [comment]
@dontcallmedom, I took a look at the #41 PR and it looks fine, just throw away references to `captureStreamUntilEnded()`.  Apologies it took me a while - other specs getting bags of action.
